name: Build Geode Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install cmake g++
        git clone https://github.com/geode-sdk/Geode.git
        cd Geode
        ./setup.sh

    - name: Build the mod
      run: |
        mkdir -p build
        cd build
        cmake ../Geode
        make

    - name: Upload Geode file
      uses: actions/upload-artifact@v2
      with:
        name: TextureRandomizer.geode
        path: build/mods/TextureRandomizer.geode
