name: Build Geode Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Geode SDK
      run: |
        sudo apt update
        sudo apt install cmake
        git clone https://github.com/geode-sdk/Geode.git
        cd Geode
        ./setup.sh

    - name: Build the mod
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Upload Geode file
      uses: actions/upload-artifact@v2
      with:
        name: TextureRandomizer.geode
        path: build/output/mod.geode
